<template>
  <div class="w-100">
    <h2 class="text-base font-medium">UUID (Universally Unique Identifier):</h2>
    <p class="py-3 rounded-sm">
      A UUID (Universally Unique Identifier) (v4) is a standardized 128-bit
      identifier used in software development to uniquely identify information
      without requiring a central authority. UUIDs are designed to be globally
      unique across space and time, ensuring no two UUIDs are alike, even if
      generated by different systems at different times.
    </p>
    <div class="flex gap-3 items-center">
      <p class="text-center w-3/4 bg-slate-100 p-3 rounded-lg text-lg">
        {{ uuid }}
      </p>
      <button
        @click="copyUUid(uuid)"
        class="bg-slate-300 h-10 text-center px-3 rounded-md hover:bg-slate-400 hover:shadow-md"
      >
        Copy
      </button>
      <button
        @click="generateUUID"
        class="bg-primary-500 h-10 text-center px-3 rounded-md hover:bg-primary-800 hover:shadow-md text-white"
      >
        Generate
      </button>
    </div>
  </div>
</template>
<script setup>
import { ref, onMounted } from "vue";

const uuid = ref(null);
onMounted(() => {
  generateUUID();
});
const generateUUID = () => {
  let d = new Date().getTime();
  let d2 = (performance && performance.now && performance.now() * 1000) || 0;
  uuid.value = "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(
    /[xy]/g,
    function (c) {
      let r = Math.random() * 16;
      if (d > 0) {
        r = (d + r) % 16 | 0;
        d = Math.floor(d / 16);
      } else {
        r = (d2 + r) % 16 | 0;
        d2 = Math.floor(d2 / 16);
      }
      return (c === "x" ? r : (r & 0x3) | 0x8).toString(16);
    }
  );
};
const copyUUid = (textToCopy) => {
  const textArea = document.createElement("textarea");
  textArea.value = textToCopy;
  document.body.appendChild(textArea);
  textArea.select();
  document.execCommand("copy");
  document.body.removeChild(textArea);
  alert("Text copied to clipboard!");
};
</script>
<style></style>
